<?php
/**
 * CCOS claim counter — shared-hosting variant (single-file PHP, no framework).
 *
 * The same protocol, vault format and refusal semantics as the Rust
 * `ccos-license-server` (the canonical implementation — see ../src/lib.rs and
 * docs/LICENSING_SERVER.md): a claim code is a bearer secret whose single-use
 * property is a state flip in vault.json, performed under an exclusive lock
 * and persisted BEFORE the signed token is disclosed. Tokens are ed25519,
 * signed with libsodium (bundled in PHP ≥ 7.2) — byte-identical to the Rust
 * signer for the same payload (`php claim.php selftest` proves it against a
 * vector generated by the Rust code).
 *
 * Why this file exists: the counter's state lives in vault.json, not in a
 * process — so a script invoked per request (classic shared-hosting PHP) is a
 * perfectly sound deployment. No daemon, no systemd, no open port to manage;
 * the hoster's TLS does the transport.
 *
 * Endpoints (same one file):
 *   POST + JSON body      → the API `ccos license claim` speaks (ccos.claim/v1)
 *   GET                   → a small human form (paste code + machine
 *                           fingerprint from `ccos license fingerprint`)
 *   POST + form fields    → the form's result page (token to copy)
 *   CLI: php claim.php selftest → cross-implementation vector + state machine
 *
 * Deployment (see docs/LICENSING_SERVER.md, "shared hosting"):
 *   - upload this file into the webroot (e.g. www/claim.php);
 *   - put vault.json and seed.hex in a SIBLING of the webroot (NOT web-served),
 *     default ../ccos-license/ relative to this file, or override the two
 *     constants below;
 *   - manage codes with ccos-license-admin on your machine and upload
 *     vault.json over SFTP (avoid uploading while a customer is mid-claim).
 */

declare(strict_types=1);

// ── Configuration ────────────────────────────────────────────────────
// Both files must live OUTSIDE the web-served directory. seed.hex holds the
// 64-hex ed25519 signing seed on a single line (the same value the Rust
// counter takes via CCOS_LICENSE_SIGNING_SEED).
const CCOS_VAULT_PATH = __DIR__ . '/../ccos-license/vault.json';
const CCOS_SEED_PATH  = __DIR__ . '/../ccos-license/seed.hex';
const CCOS_RATE_PATH  = __DIR__ . '/../ccos-license/rate.txt';
const CCOS_RATE_MAX_PER_MIN = 30; // global — 100-bit codes need no more

const CLAIM_SCHEMA = 'ccos.claim/v1';
const VAULT_SCHEMA = 'ccos.license.vault/v1';

ini_set('display_errors', '0'); // never leak paths to clients

// ── Primitives (mirrors src/claim.rs — keep in sync) ────────────────

/** URL-safe base64 without padding (RFC 4648 §5), as the Rust b64url_encode. */
function b64url_encode(string $bytes): string
{
    return rtrim(strtr(base64_encode($bytes), '+/', '-_'), '=');
}

/** Crockford base32 alphabet used by claim codes (no I L O U). */
const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

/**
 * Normalize operator input to the canonical CCOS-XXXXX-XXXXX-XXXXX-XXXXX form
 * (case-insensitive, separators optional, O→0 and I/L→1 folded), or null.
 * Mirrors ccos::claim::canonical_code.
 */
function canonical_code(string $input): ?string
{
    $symbols = '';
    foreach (str_split($input) as $c) {
        if ($c === '-' || $c === ' ' || $c === '_' || $c === "\t") {
            continue;
        }
        $c = strtoupper($c);
        if ($c === 'O') {
            $c = '0';
        } elseif ($c === 'I' || $c === 'L') {
            $c = '1';
        }
        if (strpos(ALPHABET, $c) === false) {
            return null;
        }
        $symbols .= $c;
    }
    if (str_starts_with($symbols, 'CC0S')) {
        $symbols = substr($symbols, 4);
    }
    if (strlen($symbols) !== 20) {
        return null;
    }
    return sprintf(
        'CCOS-%s-%s-%s-%s',
        substr($symbols, 0, 5),
        substr($symbols, 5, 5),
        substr($symbols, 10, 5),
        substr($symbols, 15, 5)
    );
}

/** Domain-separated code hash — mirrors ccos::claim::code_hash. */
function code_hash(string $canonicalCode): string
{
    return hash('sha256', 'ccos-claim-code-v1|' . $canonicalCode);
}

/** Opaque machine fingerprint — mirrors ccos::claim::machine_fingerprint_of. */
function machine_fingerprint_of(string $machineId): string
{
    return hash('sha256', 'ccos-machine-v1|' . trim($machineId));
}

/** Lowercase 64-hex shape check — mirrors ccos::claim::is_sha256_hex. */
function is_sha256_hex(string $s): bool
{
    return (bool) preg_match('/^[0-9a-f]{64}$/', $s);
}

/**
 * Sign a machine-bound license token — byte-identical to the Rust
 * ccos::license::sign_token_bound for the same inputs (same field order, no
 * spaces, base64url without padding; ed25519 is deterministic so the whole
 * token matches, which the selftest asserts against a Rust-generated vector).
 */
function sign_token_bound(string $seedHex, string $licensee, ?int $exp, ?string $machine): string
{
    $payload = ['licensee' => $licensee];
    if ($exp !== null) {
        $payload['exp'] = $exp;
    }
    if ($machine !== null) {
        $payload['machine'] = $machine;
    }
    $json = json_encode($payload, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    $signingInput = b64url_encode($json);
    $keypair = sodium_crypto_sign_seed_keypair(hex2bin($seedHex));
    $secret = sodium_crypto_sign_secretkey($keypair);
    $sig = sodium_crypto_sign_detached($signingInput, $secret);
    return $signingInput . '.' . b64url_encode($sig);
}

// ── The vault state machine (mirrors the Rust Vault::claim) ─────────

/**
 * Claim under the already-held lock. Mutates $vault. Returns
 * [http_status, licensee|null, exp|null, error_message|null].
 */
function vault_claim(array &$vault, string $codeHash, string $machine, int $now): array
{
    if (!isset($vault['entries'][$codeHash])) {
        return [404, null, null, 'unknown claim code'];
    }
    $e = &$vault['entries'][$codeHash];
    $status = $e['status'] ?? '';
    if ($status === 'revoked') {
        return [410, null, null, 'this code was revoked by the vendor'];
    }
    if ($status === 'claimed') {
        // Same machine → idempotent re-issue with the STORED expiry (lost-token
        // self-service, never an extension); any other machine is the
        // single-seat refusal.
        if (($e['machine'] ?? null) === $machine) {
            return [200, $e['licensee'], $e['exp_unix'] ?? null, null];
        }
        return [410, null, null,
            'this code was already claimed on another machine (single-seat). Contact the vendor to re-arm it.'];
    }
    if ($status === 'unclaimed') {
        $exp = isset($e['days']) && $e['days'] !== null ? $now + ((int) $e['days']) * 86400 : null;
        $e['status'] = 'claimed';
        $e['claimed_unix'] = $now;
        if ($exp !== null) {
            $e['exp_unix'] = $exp;
        }
        $e['machine'] = $machine;
        return [200, $e['licensee'], $exp, null];
    }
    return [400, null, null, 'malformed vault entry'];
}

/**
 * The full claim transaction: lock → rate-limit → load → flip → durable save
 * → sign. The write happens BEFORE the token is disclosed; on write failure
 * nothing is issued. Returns [http_status, body_array].
 */
function handle_claim(string $codeHash, string $machine, int $now): array
{
    if (!is_sha256_hex($codeHash) || !is_sha256_hex($machine)) {
        return [400, ['error' => 'malformed claim request']];
    }
    $seedHex = trim(@file_get_contents(CCOS_SEED_PATH) ?: '');
    if (!preg_match('/^[0-9a-fA-F]{64}$/', $seedHex)) {
        // Fail closed and say so — a counter without its seed can issue nothing.
        return [500, ['error' => 'counter misconfigured (signing seed unavailable)']];
    }

    $lock = fopen(CCOS_VAULT_PATH . '.lock', 'c');
    if ($lock === false || !flock($lock, LOCK_EX)) {
        return [500, ['error' => 'counter busy — try again']];
    }
    try {
        // Global rate limit (fixed one-minute window under the same lock).
        $window = intdiv($now, 60);
        [$w, $n] = array_pad(explode(' ', trim(@file_get_contents(CCOS_RATE_PATH) ?: '')), 2, '0');
        $n = ((int) $w === $window) ? (int) $n + 1 : 1;
        @file_put_contents(CCOS_RATE_PATH, $window . ' ' . $n);
        if ($n > CCOS_RATE_MAX_PER_MIN) {
            return [429, ['error' => 'rate limited — try again shortly']];
        }

        $raw = @file_get_contents(CCOS_VAULT_PATH);
        if ($raw === false) {
            return [500, ['error' => 'counter misconfigured (vault unavailable)']];
        }
        $vault = json_decode($raw, true);
        if (!is_array($vault) || ($vault['schema'] ?? '') !== VAULT_SCHEMA) {
            return [500, ['error' => 'counter misconfigured (vault unreadable)']];
        }

        [$status, $licensee, $exp, $err] = vault_claim($vault, $codeHash, $machine, $now);
        if ($status !== 200) {
            return [$status, ['error' => $err]];
        }

        // Durable-ish persist inside the lock: temp sibling + atomic rename.
        $json = json_encode($vault, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
        $tmp = CCOS_VAULT_PATH . '.tmp';
        if (@file_put_contents($tmp, $json) === false || !@rename($tmp, CCOS_VAULT_PATH)) {
            @unlink($tmp);
            return [500, ['error' => 'persistence failure — nothing was issued']];
        }

        $token = sign_token_bound($seedHex, $licensee, $exp, $machine);
        return [200, ['token' => $token]];
    } finally {
        flock($lock, LOCK_UN);
        fclose($lock);
    }
}

// ── Self-test (CLI): the cross-implementation contract ──────────────

if (PHP_SAPI === 'cli') {
    if (($argv[1] ?? '') !== 'selftest') {
        fwrite(STDERR, "usage: php claim.php selftest\n");
        exit(2);
    }
    $fail = function (string $what): void {
        fwrite(STDERR, "✗ {$what}\n");
        exit(1);
    };

    // Vector generated by the Rust implementation (seed = 32×0x07,
    // licensee "vector-corp", exp 1234567890, machine id "vector-machine").
    $seedHex = str_repeat('07', 32);
    $machineFp = machine_fingerprint_of('vector-machine');
    $machineFp === '6bb5b5a8623e94d18062c8ac5f37746f095bc93f9522307371c1bec7928a7c47'
        || $fail('machine fingerprint diverges from the Rust implementation');
    code_hash('CCOS-AAAAA-AAAAA-AAAAA-AAAAA')
        === '387c45ee5457f5e622d1b35c7c1afc302097a81880416bdab8352a2fa7345d79'
        || $fail('code hash diverges from the Rust implementation');
    $expected = 'eyJsaWNlbnNlZSI6InZlY3Rvci1jb3JwIiwiZXhwIjoxMjM0NTY3ODkwLCJtYWNoaW5lIjoiNmJiNWI1YTg2MjNlOTRkMTgwNjJjOGFjNWYzNzc0NmYwOTViYzkzZjk1MjIzMDczNzFjMWJlYzc5MjhhN2M0NyJ9.ceoCvEpnrf-AgYInOM3vREdXYj2RoR0XGZ7sHvZuj8NTveT6ySqTb0O4UHJiyreQ_L_PPIroCtYieT6_G6x4Bg';
    sign_token_bound($seedHex, 'vector-corp', 1234567890, $machineFp) === $expected
        || $fail('signed token is not byte-identical to the Rust signer');
    // And the signature verifies against the seed's public half.
    [$si, $sig] = explode('.', $expected);
    $pk = sodium_crypto_sign_publickey(sodium_crypto_sign_seed_keypair(hex2bin($seedHex)));
    sodium_crypto_sign_verify_detached(
        base64_decode(strtr($sig, '-_', '+/')),
        $si,
        $pk
    ) || $fail('token signature does not verify');

    // Canonicalization mirrors the Rust rules.
    canonical_code('ccos-j9vkd mm9js-65g2h_ymb96') === 'CCOS-J9VKD-MM9JS-65G2H-YMB96'
        || $fail('canonical_code folding diverges');
    canonical_code('CCOS-SHORT') === null || $fail('short code must be refused');

    // The state machine on a throwaway vault: claim → reissue → seat taken →
    // revoked → (rearm is the admin CLI's job, not the endpoint's).
    $vault = ['schema' => VAULT_SCHEMA, 'entries' => [
        'h1' => ['licensee' => 'Acme', 'days' => 365, 'status' => 'unclaimed', 'created_unix' => 1],
    ]];
    $now = 1000000;
    [$s,, $exp,] = vault_claim($vault, 'h1', 'm1', $now);
    ($s === 200 && $exp === $now + 365 * 86400) || $fail('first claim must issue with now+365d');
    [$s,, $exp2,] = vault_claim($vault, 'h1', 'm1', $now + 5000);
    ($s === 200 && $exp2 === $exp) || $fail('same-machine re-claim must re-issue the SAME expiry');
    [$s,,,] = vault_claim($vault, 'h1', 'm2', $now);
    $s === 410 || $fail('another machine must be refused (single-seat)');
    [$s,,,] = vault_claim($vault, 'nope', 'm1', $now);
    $s === 404 || $fail('unknown code must 404');
    $vault['entries']['h1']['status'] = 'revoked';
    [$s,,,] = vault_claim($vault, 'h1', 'm1', $now);
    $s === 410 || $fail('revoked code must 410');

    echo "✓ selftest passed — token byte-identical to the Rust signer; state machine conforms\n";
    exit(0);
}

// ── HTTP routing ─────────────────────────────────────────────────────

header('X-Content-Type-Options: nosniff');
// Tokens are bearer material: no intermediary (proxy, hosting cache, browser)
// may ever store a response from this endpoint.
header('Cache-Control: no-store, max-age=0');
header('Referrer-Policy: no-referrer');
$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
$now = time();

/** Emit a JSON response and stop. */
function respond_json(int $status, array $body): void
{
    http_response_code($status);
    header('Content-Type: application/json');
    echo json_encode($body, JSON_UNESCAPED_SLASHES);
    exit;
}

if ($method === 'POST' && empty($_POST)) {
    // The API path `ccos license claim` speaks: a raw JSON body.
    $req = json_decode(file_get_contents('php://input') ?: '', true);
    if (!is_array($req) || ($req['schema'] ?? '') !== CLAIM_SCHEMA) {
        respond_json(400, ['error' => 'malformed claim request']);
    }
    [$status, $body] = handle_claim(
        (string) ($req['code_hash'] ?? ''),
        (string) ($req['machine'] ?? ''),
        $now
    );
    respond_json($status, $body);
}

// ── The human form (GET renders it; form-POST redeems) ──────────────

function page(string $bodyHtml, int $status = 200): void
{
    http_response_code($status);
    header('Content-Type: text/html; charset=utf-8');
    echo "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">"
        . "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
        . "<title>CCOS Pro — license claim</title><style>"
        . "body{font:16px/1.5 system-ui,sans-serif;max-width:38rem;margin:3rem auto;padding:0 1rem;color:#222}"
        . "input,textarea{width:100%;font:14px/1.4 ui-monospace,monospace;padding:.5rem;margin:.25rem 0 1rem;box-sizing:border-box}"
        . "button{font:16px system-ui;padding:.5rem 1.25rem}"
        . "code,pre{font-family:ui-monospace,monospace;background:#f4f4f4;padding:.1rem .3rem}"
        . ".err{color:#a4262c}.ok{color:#0b6a0b}"
        . "</style></head><body><h1>CCOS Pro — license claim</h1>{$bodyHtml}"
        . "<hr><p><small>Nothing but two hashes is sent; the token is verified "
        . "on your machine against the key baked into your binary. Prefer the "
        . "CLI: <code>ccos license claim &lt;CODE&gt; --from &lt;this site&gt;</code></small></p>"
        . "</body></html>";
    exit;
}

$formHtml = static function (string $notice = ''): string {
    $esc = static fn(string $s): string => htmlspecialchars($s, ENT_QUOTES);
    return $notice
        . "<form method=\"post\">"
        . "<label>Claim code (from your invoice)</label>"
        . "<input name=\"code\" placeholder=\"CCOS-XXXXX-XXXXX-XXXXX-XXXXX\" required>"
        . "<label>Machine fingerprint — run <code>ccos license fingerprint</code> on the machine to license</label>"
        . "<input name=\"machine\" placeholder=\"64 hex characters\" required pattern=\"[0-9a-fA-F]{64}\">"
        . "<button>Claim the license</button></form>";
};

if ($method === 'GET') {
    page($formHtml());
}

if ($method === 'POST') {
    $code = canonical_code((string) ($_POST['code'] ?? ''));
    $machine = strtolower(trim((string) ($_POST['machine'] ?? '')));
    if ($code === null) {
        page($formHtml('<p class="err">That is not a claim code (expected CCOS-XXXXX-XXXXX-XXXXX-XXXXX).</p>'), 400);
    }
    if (!is_sha256_hex($machine)) {
        page($formHtml('<p class="err">The machine fingerprint must be the 64-hex output of <code>ccos license fingerprint</code>.</p>'), 400);
    }
    [$status, $body] = handle_claim(code_hash($code), $machine, $now);
    if ($status !== 200) {
        page($formHtml('<p class="err">' . htmlspecialchars((string) $body['error'], ENT_QUOTES) . '</p>'), $status);
    }
    $token = htmlspecialchars((string) $body['token'], ENT_QUOTES);
    page(
        '<p class="ok">✓ License issued — single seat, bound to your machine.</p>'
        . '<p>Save this token on the licensed machine as <code>~/.config/ccos/license</code> '
        . '(or <code>$CCOS_LICENSE_FILE</code>), then run <code>ccos doctor</code>:</p>'
        . "<textarea rows=\"6\" readonly onclick=\"this.select()\">{$token}</textarea>"
    );
}

http_response_code(405);
header('Content-Type: application/json');
echo '{"error":"method not allowed"}';
