#!/usr/bin/env bash
# check-author-policy.sh — enforce the single-human-contributor policy (§13, §43).
#
# What is forbidden:
#   - any author/committer identity other than ZEKRITI Tarek;
#   - AI or bot identities (Claude, Codex, ChatGPT, Copilot, Gemini, Kimi, …);
#   - contribution trailers (Co-authored-by, Generated-by, …);
#   - AI-attribution phrases ("generated by/with …", "AI-generated", session trailers).
#
# What is ALLOWED: technical references to model providers (Anthropic, OpenAI,
# Ollama, …) — the project ships provider adapters (mission §30). Attribution
# is forbidden, interoperability is not.
#
# Usage:
#   scripts/check-author-policy.sh           # check HEAD commit
#   scripts/check-author-policy.sh A..B      # check a commit range
set -euo pipefail
cd "$(dirname "$0")/.."

RANGE="${1:-HEAD}"
EXPECTED_NAME="ZEKRITI Tarek"

IDENTITY_RE='claude|anthropic|chatgpt|codex|copilot|gemini|kimi|opencode|\bbot\b|noreply@anthropic'
TRAILER_RE='^(co-?authored-by|co-developed-by|contributed-by|generated-by|assisted-by|suggested-by|[a-z-]*-session)\s*:'
ATTRIBUTION_RE='generated (by|with) (claude|chatgpt|codex|copilot|gemini|kimi|opencode|ai)|ai[- ]generated|ai[- ]assisted|written by (claude|chatgpt|codex|kimi|ai)'

fail=0
while IFS=$'\t' read -r h an ae cn ce; do
  if [ "$an" != "$EXPECTED_NAME" ] || [ "$cn" != "$EXPECTED_NAME" ]; then
    echo "::error::$h author/committer is '$an'/'$cn', expected '$EXPECTED_NAME'"
    fail=1
  fi
  if echo "$an$ae$cn$ce" | grep -Eiq "$IDENTITY_RE"; then
    echo "::error::$h AI/bot identity detected"
    fail=1
  fi
  if git log -1 --format='%B' "$h" | grep -Eiq "$TRAILER_RE"; then
    echo "::error::$h forbidden contribution trailer"
    fail=1
  fi
  if git log -1 --format='%B' "$h" | grep -Eiq "$ATTRIBUTION_RE"; then
    echo "::error::$h AI attribution phrase in commit message"
    fail=1
  fi
done < <(git log --format='%H%x09%an%x09%ae%x09%cn%x09%ce' "$RANGE")

if [ "$fail" -ne 0 ]; then
  echo "AUTHOR POLICY: FAILED"
  exit 1
fi
echo "AUTHOR POLICY: PASS ($RANGE)"
